  import 'package:jikan_api/jikan_api.dart';

List categoriesList = [
    "action",
    "adventure",
    "cars",
    "comedy",
    "dementia",
    "demons",
    "mystery",
    "drama",
    "ecchi",
    "fantasy",
    "game",
    "hentai",
    "historical",
    "horror",
    "kids",
    "magic",
    "martial Arts",
    "mecha",
    "music",
    "parody",
    "samurai",
    "romance",
    "school",
    "sciFi",
    "shoujo",
    "shoujo Ai",
    "shounen",
    "shounenAi",
    "space",
    "sports",
    "super Power",
    "vampire",
    "yaoi",
    "yuri",
    "harem",
    "slice of Life",
    "supernatural",
    "military",
    "police",
    "psychological",
    "thriller",
    "seinen",
    "josei",
    "doujinshi",
    "gender bender"
  ];

  List genres = [
    Genre.action,
    Genre.adventure,
    Genre.cars,
    Genre.comedy,
    Genre.dementia,
    Genre.demons,
    Genre.mystery,
    Genre.drama,
    Genre.ecchi,
    Genre.fantasy,
    Genre.game,
    Genre.hentai,
    Genre.historical,
    Genre.horror,
    Genre.kids,
    Genre.magic,
    Genre.martialArts,
    Genre.mecha,
    Genre.music,
    Genre.parody,
    Genre.samurai,
    Genre.romance,
    Genre.school,
    Genre.sciFi,
    Genre.shoujo,
    Genre.shoujoAi,
    Genre.shounen,
    Genre.shounenAi,
    Genre.space,
    Genre.sports,
    Genre.superPower,
    Genre.vampire,
    Genre.yaoi,
    Genre.yuri,
    Genre.harem,
    Genre.sliceOfLife,
    Genre.supernatural,
    Genre.military,
    Genre.police,
    Genre.psychological,
    Genre.thriller,
    Genre.seinen,
    Genre.josei,
    Genre.doujinshi,
    Genre.genderBender
  ];